CREATE DATABASE PastureManagement
GO

USE PastureManagement

GO
CREATE TABLE PMUser(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	UserName VARCHAR(30) NOT NULL,
	Telephone VARCHAR(11) NOT NULL,
	Email VARCHAR(40) NOT NULL,
    PasswordHash  VARCHAR(10) NOT NULL,
	Office VARCHAR(20) NOT NULL,
	RoleId VARCHAR(30) NOT NULL,
	Estado BIT NOT NULL,
);
GO
CREATE TABLE Farm(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (UserId) REFERENCES PMUser (Id),
	FarmName VARCHAR(40) NOT NULL,
	Document VARCHAR(16) NOT NULL,
	Area DOUBLE PRECISION NOT NULL,
	FarmAddress VARCHAR(50) NOT NULL,
	City VARCHAR(30) NOT NULL,
	UF NVARCHAR(2) NOT NULL,
);

GO
CREATE TABLE Pasture(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	FarmId UNIQUEIDENTIFIER NOT NULL
	FOREIGN KEY (UserId) REFERENCES PMUser (Id),
	FOREIGN KEY (FarmId) REFERENCES Farm (Id),
	PastureName VARCHAR(10) NOT NULL,
	Area DOUBLE PRECISION NOT NULL,
	GrassType VARCHAR (20) NOT NULL,
	PastureDescription VARCHAR (100) NOT NULL,
	DataInitial DATETIME NOT NULL,
	QtdAnimals INT NOT NULL,
	WeightMedium DOUBLE PRECISION NOT NULL,
	WeightTotal  DOUBLE PRECISION NOT NULL,
	TypeFlock VARCHAR(15) NOT NULL,
	Race VARCHAR(15) NOT NULL,
	AgeMonths DATETIME NOT NULL,
	Sexo VARCHAR(10),
	CapacityUA DOUBLE PRECISION NOT NULL,
	RateCapacityUA DOUBLE PRECISION NOT NULL,
	RateFractional DOUBLE PRECISION NOT NULL,
	Condition VARCHAR(15) NOT NULL
);
GO
CREATE TABLE Evaluation(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	FarmId UNIQUEIDENTIFIER NOT NULL,
	PastureId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (UserId) REFERENCES PMUser (Id),
	FOREIGN KEY (FarmId) REFERENCES Farm (Id),
	FOREIGN KEY (PastureId) REFERENCES Pasture (Id),
	Period VARCHAR(11) NOT NULL,
	QtdLeaf DOUBLE PRECISION NOT NULL,
	RFS DOUBLE PRECISION NOT NULL,
	NFV DOUBLE PRECISION NOT NULL,
	Note DOUBLE PRECISION NOT NULL,
	EvaluationDate DATETIME NOT NULL,
	
);

  SELECT * FROM Pasture
  SELECT * FROM Evaluation
  SELECT * FROM PMUser

